# Generated by Django 2.1.4 on 2018-12-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_serviceobject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='serviceobject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='tankreading',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ServiceObject'),
        ),
    ]
